### ISSUE TITLE
Completely unable to launch

### ISSUE THREAD

**Issue by smit283336** [ambiguousname/jackbox-custom-content#12] opened 2024-09-16 17:26 UTC
When I found this program just randomly through Google, I got so excited! My family and I play Blather Round all the time, so custom prompts would be a godsend.

I followed the installation directions on the readme file, but the exe refuses to load. I get a blank command prompt window, and then a few seconds after, I get the below error message. And once I click OK, it closes itself.
![image](https://github.com/user-attachments/assets/7e6ccdfb-594d-4bb7-950e-11efb2d1b73c)

I'm not sure what I'm doing wrong, the files are in the right directory as the instructions provided (C:\Program Files x86\Steam\steamapps\common\The Jackbox Party Pack 7\games).
![image (1)](https://github.com/user-attachments/assets/10bb7c73-e931-4780-9666-62c156d1e19c)

I tried the Python file as well, but that didn't do anything at all.

Not sure how active you are, but if you're able to look into this, I'd greatly appreciate it! The download I used was the newest version 1.0.1, if that helps.

**Comment by ambiguousname** [comment] 2024-09-16 18:55
Thanks for checking this out!

Jackbox recently put out an update it looks like, which broke the folder structure that the program uses to determine whether or not it's in the games folder.

The fix is quite simple, just create a folder called `PartyPack` in the `/games` folder, and everything should run as intended. I'll patch the executable soon!

**Comment by ambiguousname** [comment] 2024-09-16 19:08
Fixed in 1.0.2: https://github.com/ambiguousname/jackbox-custom-content/releases/tag/1.02

**Closed as completed** 2024-09-16 19:08 UTC

**Comment by smit283336** [comment] 2024-09-16 20:18
I wasn't expecting such a fast response, thank you! Makes sense the Megapicker updates would have tampered with some stuff. But the 1.0.2 release works perfectly now!
